// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ColorPicker: typeof import('./src/components/color-picker/src/color-picker.vue')['default']
    CoordinateSystemInfo: typeof import('./src/components/coordinte-system-info/src/coordinate-system-info.vue')['default']
    DirectoryTree: typeof import('./src/components/directory-tree/src/directory-tree.vue')['default']
    Drag: typeof import('./src/components/drag/index.vue')['default']
    Editor: typeof import('./src/components/vector-editor/src/editor.vue')['default']
    EnumSelect: typeof import('./src/components/enum-select/src/enum-select.vue')['default']
    GroupBox: typeof import('./src/components/group-box/src/group-box.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    InputLength: typeof import('./src/components/input-length/src/input-length.vue')['default']
    InputNumber: typeof import('./src/components/input-number/src/input-number.vue')['default']
    InputSavePath: typeof import('./src/components/input-save-path/src/input-save-path.vue')['default']
    InputSelectPath: typeof import('./src/components/input-select-path/src/input-select-path.vue')['default']
    LayerFieldSelect: typeof import('./src/components/layer-field-select/src/layer-field-select.vue')['default']
    ListBox: typeof import('./src/components/list-box/src/list-box.vue')['default']
    MapLayerSelect: typeof import('./src/components/map-layer-select/src/map-layer-select.vue')['default']
    Panel: typeof import('./src/components/panel/index.vue')['default']
    Resize: typeof import('./src/components/resize/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBox: typeof import('./src/components/scroll-box/src/scroll-box.vue')['default']
    SelectCoordinateSystem: typeof import('./src/components/select-coordinate-system/src/select-coordinate-system.vue')['default']
    SqliteColumnType: typeof import('./src/components/sqlite-column-type/index.vue')['default']
    Src: typeof import('./src/components/row/src/index.vue')['default']
    StatusBar: typeof import('./src/components/status-bar/src/status-bar.vue')['default']
    StepFooter: typeof import('./src/components/step-footer/index.vue')['default']
    StyleIcon: typeof import('./src/components/style-icon/src/style-icon.vue')['default']
    TableStructure: typeof import('./src/components/table-structure/src/table-structure.vue')['default']
    TableStructureCompare: typeof import('./src/components/table-structure-compare/src/table-structure-compare.vue')['default']
    Timer: typeof import('./src/components/timer/index.vue')['default']
    ToolContainer: typeof import('./src/components/tool-container/src/tool-container.vue')['default']
    VectorEditor: typeof import('./src/components/vector-editor/src/vector-editor.vue')['default']
    WindowControls: typeof import('./src/components/window-controls/index.vue')['default']
  }
}
